# Generated by Django 4.2.2 on 2023-07-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carstore',
            name='imageUrl',
            field=models.CharField(max_length=1000),
        ),
    ]
