# Generated by Django 4.2.2 on 2023-07-06 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_eid_users_epassword'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='UserInfo',
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='userinfo',
        ),
    ]
