# Generated by Django 4.2.2 on 2023-07-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('price', models.CharField(max_length=400)),
                ('imageUrl', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'featuredcars',
            },
        ),
    ]
